### ISSUE TITLE
Practica1_Validacion de Propuesta de Valor

### ISSUE THREAD

**Issue by Brendalp** [SistemasTecTlaxiaco/practica-de-validacion-de-propuesta-de-valor-trabajo-is#2]
[Practica1_Validacion de Propuesta de Valor.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-validacion-de-propuesta-de-valor-trabajo-is/files/6174114/Practica1_Validacion.de.Propuesta.de.Valor.pdf)

**Comment by Anthony4523** [comment]
Calificación: 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
