### ISSUE TITLE
Practica1_Validacion de Propuesta de Valor

### ISSUE THREAD

**Issue by Brendalp** [SistemasTecTlaxiaco/practica-de-validacion-de-propuesta-de-valor-trabajo-is#3]
[Practica2_Costos del proyecto.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-validacion-de-propuesta-de-valor-trabajo-is/files/6174116/Practica2_Costos.del.proyecto.pdf)

**Comment by Anthony4523** [comment]
Calificación: 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
